### ISSUE TITLE
training and testing

### ISSUE THREAD

**Issue by yinxu1996** [hw654833612/Visual-Language-Decoding#1]
Dear author, hello! I have a question that troubles me: your tasks are catagory decoding and labeling decoding, but you use image category and labeling as inputs to train the model? What are the inputs for the model testing phase?

**Comment by hw654833612** [comment]
The input is visual neural activities



---- Replied Message ----
| From | Yin ***@***.***> |
| Date | 07/20/2024 11:04 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [hw654833612/Visual-Language-Decoding] training and testing (Issue #1) |

Dear author, hello! I have a question that troubles me: your tasks are catagory decoding and labeling decoding, but you use image category and labeling as inputs to train the model? What are the inputs for the model testing phase?
